# Generated by Django 5.1.4 on 2024-12-26 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0004_alter_projects_status_projecttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='Project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_by', to='User_app.projects'),
            preserve_default=False,
        ),
    ]
