# Generated by Django 5.1.4 on 2024-12-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0005_projecttask_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=50),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='status',
            field=models.CharField(choices=[('to-do', 'To-Do'), ('in-progress', 'In-Progress'), ('done', 'Done')], default='to-do', max_length=50),
        ),
    ]
