# Generated by Django 5.1.4 on 2024-12-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_permission',
            field=models.BooleanField(default=False),
        ),
    ]
