# Generated by Django 5.1.4 on 2024-12-19 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_app', '0002_customuser_is_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-id']},
        ),
    ]
